spring:
  jpa:
    hibernate:
      ddt-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/aumatch?createDatabaseIfNotExist=true
    username: root
    password: maijer1245
  jackson:
    default-property-inclusion: non-null
